services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - 5678:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: